// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "qQ27AjScEO7MtO0CYWqikFRlIcBByaVIHa0GL4QBiHs2unKQwuTAulH8cVDsffS32XuxIJ";
}
}
}

